#version 460 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0) uniform sampler2D mainDepthTex;
layout(binding = 1) uniform usampler2D maskTex;
layout(binding = 2) uniform sampler2D customDepthTex;
layout(rgba16f, binding = 0) uniform image2D outputImg;

uniform bool ignoreDepth;

void main() {
    ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = textureSize(mainDepthTex, 0);
    if (texCoord.x >= size.x || texCoord.y >= size.y) return;

    uint maskData = texelFetch(maskTex, texCoord, 0).r;

    if ((maskData & 4u) == 0u) {
        imageStore(outputImg, texCoord, vec4(-1000.0));
        return;
    }


    if (ignoreDepth) {
        imageStore(outputImg, texCoord, vec4(texCoord.x, texCoord.y, 0.0, 0.0));
    } else {
        float mainDepth = texelFetch(mainDepthTex, texCoord, 0).r;
        float customDepth = texelFetch(customDepthTex, texCoord, 0).r;

        if (customDepth <= mainDepth) {
            imageStore(outputImg, texCoord, vec4(texCoord.x, texCoord.y, 0.0, 0.0));
        } else {
            imageStore(outputImg, texCoord, vec4(-1000.0));
        }
    }
}
