#version 460 core

#include "shared/shared.h"
#include "shared/uniforms.h"

struct ParticleData {
    vec4 position;
    vec4 velocity;
    vec4 lifetime;
};

layout (std430, binding = 1) restrict buffer LightInfo {
	vec4 Light_AmbientLight;
	int Light_LightCount;
	int Light_DirectionalLightCascadeCount;
	Light Light_LightsList[];
};

layout(std430, binding = 3) buffer ParticleBuffer {
    ParticleData particles[];  
};

uniform float uDeltaTime;
uniform vec3 uAreaCenter;
uniform vec3 uAreaExtents;
uniform vec3 uEmissionShapeExtents;
uniform uint uWrapAround; // change to bool
uniform uint uEnableLifetime;

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

uint hash(uint state) {
    state ^= 2747636419u;
    state *= 2654435769u;
    state ^= state >> 16;
    state *= 2654435769u;
    state ^= state >> 16;
    state *= 2654435769u;
    return state;
}

float random(inout uint state) {
    state = hash(state);
    return float(hash(state)) / 4294967295.0;
}

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= particles.length()) return;

    if (index == 0) {
		Light_LightCount = particles.length();
	}

    groupMemoryBarrier();
	barrier();

    bool justSpawned = false;

    if (particles[index].lifetime.x < 0.0 && particles[index].lifetime.x + uDeltaTime >= 0.0) {
        justSpawned = true;
    }

    particles[index].lifetime.x += uDeltaTime;

    if ((uEnableLifetime == 1 && particles[index].lifetime.x >= particles[index].lifetime.y) || justSpawned) {
        if (!justSpawned) {
            particles[index].lifetime.x = 0.0;
        }

        uint seed = index + uint(Global_Time * 1000.0);
        vec3 randomOffset = vec3(
            random(seed) * 2.0 - 1.0,
            random(seed) * 2.0 - 1.0,
            random(seed) * 2.0 - 1.0
        );

        particles[index].position.xyz = uAreaCenter + (randomOffset * uEmissionShapeExtents);
    }

    if (particles[index].lifetime.x >= 0.0) {
        particles[index].position.xyz += particles[index].velocity.xyz * uDeltaTime;
        // angle
        particles[index].lifetime.z += particles[index].lifetime.w * uDeltaTime;

        if (uWrapAround == 1) {
            vec3 localPosition = particles[index].position.xyz - uAreaCenter;
            vec3 size = uAreaExtents * 2.0;

            localPosition = mod(localPosition + uAreaExtents, size) - uAreaExtents;
            particles[index].position.xyz = uAreaCenter + localPosition;
        }
    }

    Light_LightsList[index].position = particles[index].position.xyz;
    Light_LightsList[index].type = POINT_LIGHT;
    Light_LightsList[index].range = 1f;
    Light_LightsList[index].color = vec3(1, 1, 1);
    Light_LightsList[index].intensity = 2.0f;
    Light_LightsList[index].linearAttenuation = 1.0f;
    Light_LightsList[index].quadraticAttenuation = 60.0f;
    Light_LightsList[index].shadowAtlasIndex = -1;
}
