#version 460 core

#include "shared/shared.h"
#include "shared/uniforms.h"
#include "shared/light.h"

#include "particles/shared/buffer.glsl"

uniform float uDeltaTime;
uniform vec3 uAreaCenter;
uniform vec3 uAreaExtents;
uniform vec3 uEmissionShapeExtents;
uniform uint uWrapAround; // change to bool
uniform uint uEnableLifetime;

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

#include "particles/shared/math.glsl"

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= particles.length()) return;

    bool justSpawned = false;
    if (particles[index].lifetime.x < 0.0 && particles[index].lifetime.x + uDeltaTime >= 0.0) {
        justSpawned = true;
    }

    particles[index].lifetime.x += uDeltaTime;

    if ((uEnableLifetime == 1 && particles[index].lifetime.x >= particles[index].lifetime.y) || justSpawned) {
        if (!justSpawned) {
            particles[index].lifetime.x = 0.0;
        }

        uint seed = index + uint(Global_Time * 1000.0);
        vec3 randomOffset = vec3(
            random(seed) * 2.0 - 1.0,
            random(seed) * 2.0 - 1.0,
            random(seed) * 2.0 - 1.0
        );
        particles[index].position.xyz = uAreaCenter + (randomOffset * uEmissionShapeExtents);
    }

    if (particles[index].lifetime.x >= 0.0) {
        particles[index].position.xyz += particles[index].velocity.xyz * uDeltaTime;
        // angle
        particles[index].lifetime.z += particles[index].lifetime.w * uDeltaTime;
        
        if (uWrapAround == 1) {
            vec3 localPosition = particles[index].position.xyz - uAreaCenter;
            vec3 size = uAreaExtents * 2.0;

            localPosition = mod(localPosition + uAreaExtents, size) - uAreaExtents;
            particles[index].position.xyz = uAreaCenter + localPosition;
        }
    }

    Light l;
    
    l.position = particles[index].position.xyz;
    l.type = POINT_LIGHT;
    l.range = 1.0f;
    l.color = hsl2rgb(0.1 + random(index) * 0.03, 1.0f, 0.5f);
    l.intensity = 0.3 + sin(Global_Time * (0.3 + random(index) * 0.1) + random(index) * 7) * 0.1;
    l.linearAttenuation = 1.0f;
    l.quadraticAttenuation = 60.0f;
    l.shadowAtlasIndex = -1;

    Light_AddLight(l);
}
