#version 460

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct Cluster {
	vec4 minPoint;
	vec4 maxPoint;
};

layout(std430, binding = 1) restrict buffer clusterSSBO {
	Cluster clusters[];
};

uniform float zNear;
uniform float zFar;

uniform mat4 inverseProjection;
uniform uvec2 screenDimensions;

vec3 screenToView(vec2 screenCoord) {
	vec4 ndc = vec4(screenCoord / screenDimensions * 2.0 - 1.0, -1.0, 1.0);

	vec4 viewCoord = inverseProjection * ndc;
	viewCoord /= viewCoord.w;
	return viewCoord.xyz;
}

vec3 lineIntersectionWithZPlane(vec3 startPoint, vec3 endPoint, float zDistance) {
	vec3 direction = endPoint - startPoint;
	vec3 normal = vec3(0.0, 0.0, -1.0);

	float t = (zDistance - dot(normal, startPoint)) / dot(normal, direction);
	return startPoint + t * direction;
}

void main() {
	const uvec3 gridSize = gl_NumWorkGroups;

	const uint clusterIndex = uint(dot(gl_GlobalInvocationID, vec3(1, gridSize.x, gridSize.x * gridSize.y)));

	const vec2 clusterScreenSize = screenDimensions / gridSize.xy;

	const vec2 clusterScreenMin = gl_GlobalInvocationID.xy * clusterScreenSize;
	const vec2 clusterScreenMax = (gl_GlobalInvocationID.xy + 1) * clusterScreenSize;

	const vec3 minCluster = screenToView(clusterScreenMin);
	const vec3 maxCluster = screenToView(clusterScreenMax);

	const float clusterWallNear = zNear * pow(zFar / zNear, gl_GlobalInvocationID.z / float(gridSize.z));
	const float clusterWallFar = zNear * pow(zFar / zNear, (gl_GlobalInvocationID.z + 1) / float(gridSize.z));

	const vec3 minPointNear = lineIntersectionWithZPlane(vec3(0, 0, 0), minCluster, clusterWallNear);
	const vec3 minPointFar = lineIntersectionWithZPlane(vec3(0, 0, 0), minCluster, clusterWallFar);
	const vec3 maxPointNear = lineIntersectionWithZPlane(vec3(0, 0, 0), maxCluster, clusterWallNear);
	const vec3 maxPointFar = lineIntersectionWithZPlane(vec3(0, 0, 0), maxCluster, clusterWallFar);

	clusters[clusterIndex].minPoint = vec4(min(minPointNear, minPointFar), 0);
	clusters[clusterIndex].maxPoint = vec4(max(maxPointNear, maxPointFar), 0);

	// clusters[clusterIndex].minPoint = inverseProjection[0];
	// clusters[clusterIndex].maxPoint = inverseProjection[1];
}